# Generated by Django 4.1 on 2022-12-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_portfolio"),
    ]

    operations = [
        migrations.RemoveField(model_name="portfolio", name="date",),
        migrations.AddField(
            model_name="blog",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cv"),
        ),
    ]
