# Generated by Django 4.1 on 2022-12-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_portfolio_date_blog_cv"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="cv",),
    ]
